import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const distDir = path.resolve(__dirname, '..', 'dist');

const SITE_URL = 'https://trinai.ae';
const TODAY = new Date().toISOString().split('T')[0];

// ✅ 1. All known static pages
const staticPages = [
  { path: '/',                                     changefreq: 'weekly',  priority: '1.0' },
  { path: '/services',                             changefreq: 'monthly', priority: '0.9' },
  { path: '/about',                                changefreq: 'monthly', priority: '0.8' },
  { path: '/contact',                              changefreq: 'monthly', priority: '0.8' },
  { path: '/solutions',                            changefreq: 'monthly', priority: '0.8' },
  { path: '/blog',                                 changefreq: 'daily',   priority: '0.9' },
  { path: '/surveillance-systems',                 changefreq: 'monthly', priority: '0.9' },
  { path: '/software-development',                 changefreq: 'monthly', priority: '0.9' },
  { path: '/iccc',                                 changefreq: 'monthly', priority: '0.9' },
  { path: '/home-automation',                      changefreq: 'monthly', priority: '0.9' },
  { path: '/elv-solutions',                        changefreq: 'monthly', priority: '0.9' },
  { path: '/ai-analytics',                         changefreq: 'monthly', priority: '0.9' },
  { path: '/software-development/hrms',            changefreq: 'monthly', priority: '0.8' },
  { path: '/software-development/erp',             changefreq: 'monthly', priority: '0.8' },
  { path: '/software-development/task-management', changefreq: 'monthly', priority: '0.8' },
  { path: '/software-development/anpr-solutions',  changefreq: 'monthly', priority: '0.8' },
  { path: '/software-development/custom-software', changefreq: 'monthly', priority: '0.8' },
];

// ✅ 2. Read the dist folder to find the 24 blog posts generated by the previous script
function getBlogUrlsFromDist() {
  const blogUrls = [];
  
  // Known static folders to ignore
  const staticFolders = new Set([
    'assets', 'services', 'about', 'contact', 'solutions', 'blog',
    'surveillance-systems', 'software-development', 'iccc',
    'home-automation', 'elv-solutions', 'ai-analytics'
  ]);

  if (!fs.existsSync(distDir)) return blogUrls;

  const items = fs.readdirSync(distDir, { withFileTypes: true });

  for (const item of items) {
    if (item.isDirectory() && !staticFolders.has(item.name)) {
      // Check if it has an index.html (meaning it's a generated blog post)
      const indexPath = path.join(distDir, item.name, 'index.html');
      if (fs.existsSync(indexPath)) {
        
        // ⚠️ NOTE: If your live blog URLs are https://trinai.ae/slug (without /blog/), 
        // change `/blog/${item.name}` to `/${item.name}` below.
        blogUrls.push({
          path: `/blog/${item.name}`,
          changefreq: 'monthly',
          priority: '0.7',
        });
      }
    }
  }
  return blogUrls;
}

// ✅ 3. Generate the XML
function generateSitemap() {
  const blogUrls = getBlogUrlsFromDist();
  const allPages = [...staticPages, ...blogUrls];

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

  for (const page of allPages) {
    xml += `  <url>\n    <loc>${SITE_URL}${page.path}</loc>\n    <lastmod>${TODAY}</lastmod>\n    <changefreq>${page.changefreq}</changefreq>\n    <priority>${page.priority}</priority>\n  </url>\n`;
  }

  xml += `</urlset>`;

  fs.writeFileSync(path.join(distDir, 'sitemap.xml'), xml, 'utf-8');
  fs.writeFileSync(path.resolve(__dirname, '..', 'public', 'sitemap.xml'), xml, 'utf-8');

  console.log(`\n🗺️  Sitemap generated with ${allPages.length} URLs:`);
  console.log(`   📄 Static pages: ${staticPages.length}`);
  console.log(`   📝 Blog posts:   ${blogUrls.length}`);
}

generateSitemap();